### ISSUE TITLE
Support configuring more static site generators and build tools

### ISSUE THREAD

**Issue by nickmccurdy** [actions/configure-pages#30] opened 2022-09-28 05:36 UTC
## Static site generators
- [ ] Hugo
- [ ] Jekyll
- [ ] Astro

## Build tools (without prerendering)
- [ ] webpack
- [ ] create-react-app
- [ ] Vite
- [ ] Parcel

**Comment by yoannchaudet** [comment] 2022-09-28 22:14
Hugo is already supported, example: https://github.com/actions/starter-workflows/blob/main/pages/hugo.yml.

Same for Jekyll, example: https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml

Generally, static site generators that leverage CLI arguments or environment variables are all supported. Node based static generators love to have their configuration expressed as code which hinder "magic" configuration.

I have no idea what you mean by "support for build tools".

**Comment by natemoo-re** [comment] 2022-09-29 15:10
👋🏻 Hey there, core member of Astro here. Would love to help deliver official support for Astro! All the relevant config options should be supported as CLI arguments as well, but if that's not the case, we can make it happen on our end.

@nickmccurdy opened [this PR](https://github.com/withastro/action/pull/11) to add `actions/configure-pages@v2` to the official [`withastro/action`](https://github.com/withastro/action), but it didn't seem to work when I tried it. I wasn't able to debug it more... Does the `configure-pages` action only work for frameworks that are explicitly handled in this repo?

**Comment by natemoo-re** [comment] 2022-09-29 15:47
👆🏻 I realized that the Astro CLI did allow `--site` but didn't allow `--base`. That should be fixed very soon!

**Comment by yoannchaudet** [comment] 2022-09-29 17:07
@natemoo-re Correct, `configure-pages` can only inject configuration for frameworks it knows about (see [list](https://github.com/actions/configure-pages/blob/2ce6d5eaa1f7b36a30c9b424cd73fab661857cfe/src/set-pages-config.js#L11-L64)). If Astro has CLI support for configuring base/site, this is much better since we don't need to try and parse some random abstract syntax tree (i.e. configuration as code).

For a framework that has CLI support, the `congigure-pages` action can be used to just find out which URL the site will be deployed to. It gets consumed this way (example for Hugo): https://github.com/actions/starter-workflows/blob/ba77264174b7267793c7960a18718f941bf21b76/pages/hugo.yml#L51-L54

**Comment by natemoo-re** [comment] 2022-09-29 17:38
> For a framework that has CLI support, the `congigure-pages` action can be used to just find out which URL the site will be deployed to. It gets consumed this way (example for Hugo): https://github.com/actions/starter-workflows/blob/ba77264174b7267793c7960a18718f941bf21b76/pages/hugo.yml#L51-L54

Ah that's great! In that case, it probably makes the most sense to integrate `configure-pages` inside of [`withastro/action`](https://github.com/withastro/action) and then contribute a starter workflow to [`actions/starter-workflows`](https://github.com/actions/starter-workflows/)? If so, there's nothing that needs to happen in this repo.

**Comment by yoannchaudet** [comment] 2022-09-29 17:51
Correct nothing needs to happen in this repo for Astro :) (or I hope so at least). I'll be happy to help get an Astro starter workflow in `actions/starter-workflows`. @adrianmg has [opened a PR](https://github.com/actions/starter-workflows/pull/1769) already that can serve as a base (there is a bit more work needed there and hopefully if Astro can be setup with the CLI only, we could have it work for all Pages site "out of the box").

**Comment by oliverbenns** [comment] 2022-09-29 17:58
I was about to commit a pages workflow but saw this in the PR template, but then see this issue so not really sure what's happening here:

Please note that at this time we are only accepting new starter workflows for Code Scanning. Updates to existing starter workflows are fine.

I also need to sign up to be a GitHub Technology Partner. I just want to commit a yml file to help others but it seems I need to go over leaps and bounds just to contribute.

Anyway, if someone wants to take this commit for create react app, you're more than welcome: https://github.com/oliverbenns/starter-workflows/commit/dae1f02ccdb7ddca8e3bfb11b729ed69cbbf255e

**Comment by JamesMGreene** [comment] 2022-11-23 04:33
The official GitHub Pages starter workflow for Astro will soon cover the appropriate configurations via the Astro CLI `--site` and `--base` parameters: https://github.com/actions/starter-workflows/pull/1833

**Comment by JamesMGreene** [comment] 2022-11-23 04:36
Going to close this out as all of the mentioned SSGs have corresponding Pages starter workflows: https://github.com/actions/starter-workflows/blob/main/pages/

As far as supporting the random build tools, that feels out-of-scope to me. 🤷🏻‍♂️ 

If you have one you really want support for, we'd at least be open to reviewing a PR. 🔍

**Closed by JamesMGreene** 2022-11-23 04:36 UTC

**Comment by nickmccurdy** [comment] 2022-11-23 23:48
Can you please explain why you feel the build tools are out of scope? I understand GitHub Pages is frequently used with SSGs, but I also feel it's valid to use it with build tools for SPAs, which I still use frequently. I think it would be nice to have a simpler way to configure those tools for GitHub Pages, regardless of whether they prerender.

**Comment by JamesMGreene** [comment] 2022-11-26 16:06
Do keep in mind that any source that can generate a static site will work great with GitHub Pages, as you've mentioned. Likewise, you should be able to write your own custom Actions workflows that deploy to Pages for any such system regardless of if we offer an official starter workflow for it. 😊

The friction on our side is that every new official Pages starter workflow requires additional maintenance burden internally to detect, suggest, support, and verify against regressions, so it's not as simple as just adding another workflow template here.

We definitely encourage thriving communities to create custom workflows for deploying to Pages and offer them up in their own documentation or starter project scaffolding. 👍🏻
